CREATE TABLE customers(id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(50));
CREATE TABLE products(id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(50),price INT);
CREATE TABLE orders(id INT PRIMARY KEY AUTO_INCREMENT,cid INT,pid INT,qty INT);
